server:
   port: 9500
   
   
   
spring:
  cloud:
    gateway:
      routes:
        #Route Mapping
      - id: cropDetails              #RouteIdentifier
        uri: http://localhost:9000/         #Respective microservice URL which needs to be mapped
         #Request Context Path Mapping
        predicates:
        - Path=/api/crops/**          

 

        #Route Mapping - With out Filter
      - id: CartManagement
        uri: http://localhost:9200/
        predicates:
        - Path=/api/cart/**

 

        #Route Mapping - With out Filters 
      - id: OrderManagement
        uri: http://localhost:9300/
        predicates:
        - Path=/api/dealer/**
 
  application:
        name: crop-api-gateway